project:
  type: website

website:
  title: "Morris Twinomugisha"
  site-url: https://solab5.github.io/web/
  margin-header: subscribe.html
  twitter-card: True
  open-graph: True
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Blog 
      - about.qmd

      - Publication.qmd

    right:
      - icon: github
      - href: https://github.com/Solab5
      - icon: twitter
      - href: https://twitteer.com/aboutScience
format:
  html:
    theme: 
        light: cosmo 
        dark: darkly
    css: styles.css
    toc: true



