---
title: "Publications"
collection: publications
permalink: /publication/01-Research-thesis-2022
excerpt: 'A case study of Machine learning in detection of faulty devices'
date: 2022-11-01
venue: 'Machine learning in Airquality'
paperurl: 'https://www.researchgate.net/publication/366957514_UNSUPERVISED_MACHINE_LEARNING_FOR_EARLY_FAULTY_DEVICE_DETECTION?utm_source=twitter&rgutm_meta1=eHNsLWpheTh4bGtLc1RnbTRzcUVmYlVadUpaZFZlRHdmZVRUVjJ5U2JRa21ORTRxRGxYbDZEME5hQ2Zzb2UxZG50dVRsSnFBWURFWXhhTmdreldWaEpSNTY0ND0%3D'
---
Early faulty detection in air quality sensors is of increasing importance in ensuring reliable and accurate air quality readings. These sensors play a critical role in monitoring the pollution levels in the atmosphere however, due to their exposure to harsh weather, it’s natural that they will face wear and may require periodical servicing. The devices are rarely monitored in most cases, particularly in Uganda. The objective of this research is to build a model for the early detection of faulty sensors for replacement and repair. Using the unsupervised learning approaches in particular K-means and PCA; we train a predictive model and later evaluate it for accuracy using a test dataset. From the cluster analysis, the research identified 3 clusters that are; the health state cluster, nearing fault state cluster, and the faulty state cluster. The research discovered that there is no significant difference in adopting PCA as a preprocessing step in using the K-means algorithm. The research further recommended other clustering methods to be used to compare the accuracy score. It also recommended using more attributes for PCA to be effective.

Download paper on Makerere University Dissertation repository [here](http://dissertations.mak.ac.ug/bitstream/handle/20.500.12281/13852/twinomugisha-cobams-bsta.pdf?sequence=1&isAllowed=n) or research gate [here](https://www.researchgate.net/publication/366957514_UNSUPERVISED_MACHINE_LEARNING_FOR_EARLY_FAULTY_DEVICE_DETECTION?utm_source=twitter&rgutm_meta1=eHNsLWpheTh4bGtLc1RnbTRzcUVmYlVadUpaZFZlRHdmZVRUVjJ5U2JRa21ORTRxRGxYbDZEME5hQ2Zzb2UxZG50dVRsSnFBWURFWXhhTmdreldWaEpSNTY0ND0%3D)

